<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TaskManagerPro.Domain/TaskManagerPro.Domain.csproj" />
    <ProjectReference Include="../TaskManagerPro.Application/TaskManagerPro.Application.csproj" />
    <ProjectReference Include="../TaskManagerPro.Infrastructure/TaskManagerPro.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.3.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="1.23.10" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.9.0" />
  </ItemGroup>
</Project>
